apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    name: mysql
    app: odev
spec:
  selector:
    name: mysql
  type: ClusterIP
  ports:
    - name: db
      port: 3306
      targetPort: 3306
