apiVersion: v1
kind: Service
metadata:
  name: res-svc
  labels:
    name: res
    app: odev
spec:
  selector:
    name: res
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: 30002
     protocol: TCP
