version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: Ankara0666
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: jokerinya
            MYSQL_PASSWORD: Clarusway_1
        networks:
            - joker
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - joker

networks:
    joker:
        driver: bridge
